name: Bug Report
description: Tell me the all the bugs
title: "[Bug]: "
labels: "bug"
body:
  - type: markdown
    attributes:
    value: 
      Thank you for reporting all the bugs.
  - type: textarea
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: What is the bug and how did it happen?
     validations:
      required: true
