name: Bug Report
description: Tell me the all the bugs
title: "[Bug]: "
labels: "bug"
body:
  - type: markdown
    attributes:
    value: 
      Thank you for reporting all the bugs.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
