name: Ask me for a ⚡ demo
description: Request demos from Mish
title: "[Request]: "
labels: [Twitch, enhancements]
assignees:
  - MishManners
body:
  - type: markdown
    attributes:
      value: |
        Thanks for asking Mish to do a demo. Put your details below and we'll see what we can do.
  - type: dropdown
    id: ask
    attributes:
      label: type
      description: What kind of demo would you like Mish to do?
      options:
        - Issue forms
        - Task lists
        - Codespaces
        - General coding
        - GitHub for Mobile
        - GitHub Desktop
        - GitHub CLI
        - Other (elaborate below)
    validations:
      required: true

  - type: textarea
    id: More info
    attributes:
      label: More information
      description: Please add more info on the type of demo you'd like Mish to do.
      render: shell

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: checkboxes
    id: Time frame
    attributes:
      label: Timing
      description: Is this urgent of not?
      options:
        - label: Yes it is!
          required: false
  
  
